using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SSS_StoreStockSystem.DAL.Models
{
    //The relashionship between Store and Item is many-to-many, but the relashionship itself has a property (Quantity)
    //Hence, this model is manually created (not auto-generated by EF through navigation properties)
    public class StoreItem
    {
        public int StoreId { get; set; }
        public Store Store { get; set; }
        public int ItemId { get; set; }
        public Item Item { get; set; }
        public int Quantity { get; set; }
    }
}
